-- MySQL Script generated by MySQL Workbench
-- Thu Jan 28 01:31:13 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `midname` VARCHAR(45) NULL,
  `passportId` INT NULL,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `levelOFPriority` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`individual`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`individual` ;

CREATE TABLE IF NOT EXISTS `mydb`.`individual` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `midname` VARCHAR(45) NULL,
  `age` INT NULL,
  `riskcategory` INT NULL,
  `address` VARCHAR(45) NULL,
  `phonenumber` INT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_individual_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_individual_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`individualContract`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`individualContract` ;

CREATE TABLE IF NOT EXISTS `mydb`.`individualContract` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `limitation` DATE NULL,
  `amountOfPayments` INT NULL,
  `paymentsForInsuredEvents` INT NULL,
  `individual_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_individualContract_individual1_idx` (`individual_id` ASC),
  CONSTRAINT `fk_individualContract_individual1`
    FOREIGN KEY (`individual_id`)
    REFERENCES `mydb`.`individual` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`company` ;

CREATE TABLE IF NOT EXISTS `mydb`.`company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codName` INT NULL,
  `fullName` VARCHAR(45) NULL,
  `shortName` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `bankDetails` INT NULL,
  `specialization` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_company_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_company_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`collectiveContract`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`collectiveContract` ;

CREATE TABLE IF NOT EXISTS `mydb`.`collectiveContract` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `limitation` DATE NULL,
  `paymentsForInsuredEvents` INT NULL,
  `company_id` INT NOT NULL,
  `PaymentsFor1stCategory` INT NULL,
  `PaymentsFor2stCategory` INT NULL,
  `PaymentsFor3stCategory` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_collectiveContract_company1_idx` (`company_id` ASC),
  CONSTRAINT `fk_collectiveContract_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `mydb`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`companyWorker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`companyWorker` ;

CREATE TABLE IF NOT EXISTS `mydb`.`companyWorker` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `midname` VARCHAR(45) NULL,
  `age` INT NULL,
  `riskcategory` INT NULL,
  `collectiveContract_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_companyWorker_collectiveContract1_idx` (`collectiveContract_id` ASC),
  CONSTRAINT `fk_companyWorker_collectiveContract1`
    FOREIGN KEY (`collectiveContract_id`)
    REFERENCES `mydb`.`collectiveContract` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
DROP VIEW IF EXISTS `mydb`.`view1` ;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
